### ISSUE TITLE
using with CKEditor

### ISSUE THREAD

**Issue by ahmedali5530** [pjjonesnz/saveMyForm.jquery#1]
Hi
how can i use this with CKEditor?

**Comment by pjjonesnz** [comment]
Hi

See [this sandbox](https://codesandbox.io/s/ckeditor-5-savemyform-example-wuoho) as an example.

You can use it as follows: 
1. Initialize saveMyForm.jquery BEFORE you attach CKEditor to the form field/s you wish to save
2. Attach CKEditor to the form field/s with a "then" promise
3. Inside the promise, instruct CKEditor to update the source element when CKEditor changes
4. Once you do this the elements will be automatically saved and recalled when the page is revisited.

```
// First start the saveMyForm script

$("#my_form").saveMyForm();

// Then attach CKEditor to the form field/s

ClassicEditor.create(document.querySelector('#my_textarea'))

    // Add a then promise
    .then(function(editor) {

        // Once the editor is created, add the change event to update the source element 
        // automatically then trigger change on the element to cause saveMyForm to save it.

        editor.model.document.on("change", function() {
            editor.updateSourceElement();
            $(editor.sourceElement).change();
        });
    });
```
