### ISSUE TITLE
Manually load input data

### ISSUE THREAD

**Issue by joshualimsm** [pjjonesnz/saveMyForm.jquery#2]
I have a scenario where I need to change some of the form elements **before** input data is reloaded from localStorage. I know I can set `loadInputs` to false to prevent the data from being loaded when the page is re-loaded but how would I then manually load the input data?

**Comment by pjjonesnz** [comment]
Could you delay initializing the plug-in until after you've changed the form elements? Would that achieve what you wanted?

eg.

```js
$(function () {

    // your function to change your form elements
    change_form_elements();

    $("#form_id").saveMyForm();
});
```

**Comment by joshualimsm** [comment]
> Could you delay initializing the plug-in until after you've changed the form elements? Would that achieve what you wanted?

That could work. So I take it there isn't a way to manually load the data from localStorage?

**Comment by pjjonesnz** [comment]
No there isn't a way to manually run the loading of data. The only solution as it is would be to wait until your form is complete to initialize the plug-in.
